apiVersion: apps/v1
kind: Deployment
metadata:
  name: staticwebstite
  namespace: {{secrets.namespace}}
  labels:
    app: staticwebstite
spec: # Flytta spec här, inte under metadata
  replicas: 3
  selector:
    matchLabels:
      app: staticwebstite
  template:
    metadata:
      labels:
        app: staticwebstite
    spec:
      containers:
        - name: staticwebstite
          image: shenolosman/gocrudapitest
          ports:
            - containerPort: 8080
          env:
            - name: RUNENVIRONMENT
              value: Production
      imagePullSecrets:
        - name: regcred


---
apiVersion: v1
kind: Service
metadata:
  name: staticwebserver-service
  namespace: {{secrets.namespace}}
  labels:
    app: staticwebstite
spec: # Flytta spec här
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: staticwebstite
  sessionAffinity: None
