apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: golangapp-ingress
  namespace: {{secrets.namespace}}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: "shenolsgolangapp.chickenkiller.com"
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: dockersite-service
              port:
                number: 80
    - host: "mysuperdupersite.chickenkiller.com"
      http:
        paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: staticwebserver-service
              port:
                number: 80