apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{secrets.namespace}}
  name: gitea-ingress-site # here you can change the name
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod    
    nginx.ingress.kubernetes.io/proxy-body-size: "30720m"
spec:
  rules:
    - host: {{secrets.YourHostUrl}}
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: gitea-service # the name of the service for gitea
                port:
                  number: 80
  tls:
  - hosts:
    - {{secrets.YourHostUrl}} # your domain 
    secretName: letsencrypt-prod