#for cronjob in linux env
apiVersion: batch/v1
kind: CronJob
metadata:
  name: sqlbackupcron
  namespace: { { secret.namespace } }
spec:
  schedule: "30 2 * * 1,2,3,4,5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: sqlbackup
              image: docker_image_url/sqlbackup
              env:
                - name: sql_host
                  value: mysqlserver1
                - name: sql_user
                  value: sa
                - name: sql_password
                  value: hejsan123
                - name: sql_database
                  value: databaseName
          imagePullSecrets:
            - name: regcred
          restartPolicy: OnFailure
