
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: {{secrets.certificate-authority-data}}
    server: {{secrets.server}}
  name: {{secrets.clustername}}

users:
- name: {{secrets.clustername}}-admin
  user:
    as-user-extra: {}
    token: {{secrets.token}}

contexts:
- context:
    cluster: {{secrets.clustername}}
    namespace: default
    user: {{secrets.clustername}}-admin
  name: {{secrets.clustername}}-ctx

current-context: {{secrets.clustername}}-ctx
